# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from protobuffers import service_pb2 as service__pb2


class ProjectServicesStub(object):
  """The project service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Retrieve = channel.unary_unary(
        '/project.ProjectServices/Retrieve',
        request_serializer=service__pb2.ID.SerializeToString,
        response_deserializer=service__pb2.Project.FromString,
        )
    self.Create = channel.unary_unary(
        '/project.ProjectServices/Create',
        request_serializer=service__pb2.Project.SerializeToString,
        response_deserializer=service__pb2.Project.FromString,
        )
    self.Update = channel.unary_unary(
        '/project.ProjectServices/Update',
        request_serializer=service__pb2.Project.SerializeToString,
        response_deserializer=service__pb2.Project.FromString,
        )
    self.Delete = channel.unary_unary(
        '/project.ProjectServices/Delete',
        request_serializer=service__pb2.ID.SerializeToString,
        response_deserializer=service__pb2.OperationStatus.FromString,
        )
    self.Search = channel.unary_unary(
        '/project.ProjectServices/Search',
        request_serializer=service__pb2.SearchRequest.SerializeToString,
        response_deserializer=service__pb2.SearchResponse.FromString,
        )


class ProjectServicesServicer(object):
  """The project service definition.
  """

  def Retrieve(self, request, context):
    """Retrieve a project from id
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Create(self, request, context):
    """Create a project
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Update(self, request, context):
    """Update a project
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    """Delete a project from ID
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Search(self, request, context):
    """Search for projects
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProjectServicesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Retrieve': grpc.unary_unary_rpc_method_handler(
          servicer.Retrieve,
          request_deserializer=service__pb2.ID.FromString,
          response_serializer=service__pb2.Project.SerializeToString,
      ),
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=service__pb2.Project.FromString,
          response_serializer=service__pb2.Project.SerializeToString,
      ),
      'Update': grpc.unary_unary_rpc_method_handler(
          servicer.Update,
          request_deserializer=service__pb2.Project.FromString,
          response_serializer=service__pb2.Project.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=service__pb2.ID.FromString,
          response_serializer=service__pb2.OperationStatus.SerializeToString,
      ),
      'Search': grpc.unary_unary_rpc_method_handler(
          servicer.Search,
          request_deserializer=service__pb2.SearchRequest.FromString,
          response_serializer=service__pb2.SearchResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'project.ProjectServices', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
