# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='project',
  syntax='proto3',
  serialized_options=b'\n\026org.hopenly.ilyde.grpcB\014ProjectProtoP\001\242\002\002PS',
  serialized_pb=b'\n\rservice.proto\x12\x07project\x1a\x1cgoogle/protobuf/struct.proto\"\x10\n\x02ID\x12\n\n\x02id\x18\x01 \x01(\t\"2\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"\xb4\x02\n\x07Project\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\'\n\nvisibility\x18\x04 \x01(\x0e\x32\x13.project.VISIBILITY\x12#\n\x08template\x18\x05 \x01(\x0e\x32\x11.project.TEMPLATE\x12\x1c\n\x05owner\x18\x06 \x01(\x0b\x32\r.project.User\x12\x1e\n\x07members\x18\x07 \x03(\x0b\x32\r.project.User\x12\x1d\n\x05state\x18\x08 \x01(\x0e\x32\x0e.project.STATE\x12\'\n\x06labels\x18\t \x03(\x0b\x32\x17.google.protobuf.Struct\x12\x11\n\tcreate_at\x18\n \x01(\t\x12\x13\n\x0blast_update\x18\x0b \x01(\t\"2\n\x0fOperationStatus\x12\x0e\n\x06status\x18\x01 \x01(\r\x12\x0f\n\x07message\x18\x02 \x01(\t\"f\n\rSearchRequest\x12\'\n\x06\x66ilter\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x13\n\x0bpage_number\x18\x02 \x01(\x05\x12\x17\n\x0fresult_per_page\x18\x03 \x01(\x05\"q\n\x0eSearchResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x13\n\x0bpage_number\x18\x02 \x01(\x05\x12\x17\n\x0fresult_per_page\x18\x03 \x01(\x05\x12\"\n\x08projects\x18\x04 \x03(\x0b\x32\x10.project.Project*%\n\nVISIBILITY\x12\x0b\n\x07PRIVATE\x10\x00\x12\n\n\x06PUBLIC\x10\x01*\x1d\n\x05STATE\x12\x08\n\x04OPEN\x10\x00\x12\n\n\x06\x43LOSED\x10\x01*\x17\n\x08TEMPLATE\x12\x0b\n\x07SKLEARN\x10\x00\x32\x8e\x02\n\x0fProjectServices\x12+\n\x08Retrieve\x12\x0b.project.ID\x1a\x10.project.Project\"\x00\x12.\n\x06\x43reate\x12\x10.project.Project\x1a\x10.project.Project\"\x00\x12.\n\x06Update\x12\x10.project.Project\x1a\x10.project.Project\"\x00\x12\x31\n\x06\x44\x65lete\x12\x0b.project.ID\x1a\x18.project.OperationStatus\"\x00\x12;\n\x06Search\x12\x16.project.SearchRequest\x1a\x17.project.SearchResponse\"\x00\x42-\n\x16org.hopenly.ilyde.grpcB\x0cProjectProtoP\x01\xa2\x02\x02PSb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])

_VISIBILITY = _descriptor.EnumDescriptor(
  name='VISIBILITY',
  full_name='project.VISIBILITY',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PRIVATE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUBLIC', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=708,
  serialized_end=745,
)
_sym_db.RegisterEnumDescriptor(_VISIBILITY)

VISIBILITY = enum_type_wrapper.EnumTypeWrapper(_VISIBILITY)
_STATE = _descriptor.EnumDescriptor(
  name='STATE',
  full_name='project.STATE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OPEN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSED', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=747,
  serialized_end=776,
)
_sym_db.RegisterEnumDescriptor(_STATE)

STATE = enum_type_wrapper.EnumTypeWrapper(_STATE)
_TEMPLATE = _descriptor.EnumDescriptor(
  name='TEMPLATE',
  full_name='project.TEMPLATE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SKLEARN', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=778,
  serialized_end=801,
)
_sym_db.RegisterEnumDescriptor(_TEMPLATE)

TEMPLATE = enum_type_wrapper.EnumTypeWrapper(_TEMPLATE)
PRIVATE = 0
PUBLIC = 1
OPEN = 0
CLOSED = 1
SKLEARN = 0



_ID = _descriptor.Descriptor(
  name='ID',
  full_name='project.ID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='project.ID.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=72,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='project.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='project.User.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='project.User.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='project.User.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=124,
)


_PROJECT = _descriptor.Descriptor(
  name='Project',
  full_name='project.Project',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='project.Project.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='project.Project.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='project.Project.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visibility', full_name='project.Project.visibility', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='template', full_name='project.Project.template', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner', full_name='project.Project.owner', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='members', full_name='project.Project.members', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='project.Project.state', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='labels', full_name='project.Project.labels', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_at', full_name='project.Project.create_at', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_update', full_name='project.Project.last_update', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=435,
)


_OPERATIONSTATUS = _descriptor.Descriptor(
  name='OperationStatus',
  full_name='project.OperationStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='project.OperationStatus.status', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='project.OperationStatus.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=437,
  serialized_end=487,
)


_SEARCHREQUEST = _descriptor.Descriptor(
  name='SearchRequest',
  full_name='project.SearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filter', full_name='project.SearchRequest.filter', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_number', full_name='project.SearchRequest.page_number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result_per_page', full_name='project.SearchRequest.result_per_page', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=489,
  serialized_end=591,
)


_SEARCHRESPONSE = _descriptor.Descriptor(
  name='SearchResponse',
  full_name='project.SearchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total', full_name='project.SearchResponse.total', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_number', full_name='project.SearchResponse.page_number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result_per_page', full_name='project.SearchResponse.result_per_page', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='projects', full_name='project.SearchResponse.projects', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=593,
  serialized_end=706,
)

_PROJECT.fields_by_name['visibility'].enum_type = _VISIBILITY
_PROJECT.fields_by_name['template'].enum_type = _TEMPLATE
_PROJECT.fields_by_name['owner'].message_type = _USER
_PROJECT.fields_by_name['members'].message_type = _USER
_PROJECT.fields_by_name['state'].enum_type = _STATE
_PROJECT.fields_by_name['labels'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_SEARCHREQUEST.fields_by_name['filter'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_SEARCHRESPONSE.fields_by_name['projects'].message_type = _PROJECT
DESCRIPTOR.message_types_by_name['ID'] = _ID
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Project'] = _PROJECT
DESCRIPTOR.message_types_by_name['OperationStatus'] = _OPERATIONSTATUS
DESCRIPTOR.message_types_by_name['SearchRequest'] = _SEARCHREQUEST
DESCRIPTOR.message_types_by_name['SearchResponse'] = _SEARCHRESPONSE
DESCRIPTOR.enum_types_by_name['VISIBILITY'] = _VISIBILITY
DESCRIPTOR.enum_types_by_name['STATE'] = _STATE
DESCRIPTOR.enum_types_by_name['TEMPLATE'] = _TEMPLATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ID = _reflection.GeneratedProtocolMessageType('ID', (_message.Message,), {
  'DESCRIPTOR' : _ID,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:project.ID)
  })
_sym_db.RegisterMessage(ID)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:project.User)
  })
_sym_db.RegisterMessage(User)

Project = _reflection.GeneratedProtocolMessageType('Project', (_message.Message,), {
  'DESCRIPTOR' : _PROJECT,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:project.Project)
  })
_sym_db.RegisterMessage(Project)

OperationStatus = _reflection.GeneratedProtocolMessageType('OperationStatus', (_message.Message,), {
  'DESCRIPTOR' : _OPERATIONSTATUS,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:project.OperationStatus)
  })
_sym_db.RegisterMessage(OperationStatus)

SearchRequest = _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:project.SearchRequest)
  })
_sym_db.RegisterMessage(SearchRequest)

SearchResponse = _reflection.GeneratedProtocolMessageType('SearchResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHRESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:project.SearchResponse)
  })
_sym_db.RegisterMessage(SearchResponse)


DESCRIPTOR._options = None

_PROJECTSERVICES = _descriptor.ServiceDescriptor(
  name='ProjectServices',
  full_name='project.ProjectServices',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=804,
  serialized_end=1074,
  methods=[
  _descriptor.MethodDescriptor(
    name='Retrieve',
    full_name='project.ProjectServices.Retrieve',
    index=0,
    containing_service=None,
    input_type=_ID,
    output_type=_PROJECT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='project.ProjectServices.Create',
    index=1,
    containing_service=None,
    input_type=_PROJECT,
    output_type=_PROJECT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='project.ProjectServices.Update',
    index=2,
    containing_service=None,
    input_type=_PROJECT,
    output_type=_PROJECT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='project.ProjectServices.Delete',
    index=3,
    containing_service=None,
    input_type=_ID,
    output_type=_OPERATIONSTATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='project.ProjectServices.Search',
    index=4,
    containing_service=None,
    input_type=_SEARCHREQUEST,
    output_type=_SEARCHRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROJECTSERVICES)

DESCRIPTOR.services_by_name['ProjectServices'] = _PROJECTSERVICES

# @@protoc_insertion_point(module_scope)
